### ISSUE TITLE
Error occurred when executing InsightFaceLoader_Zho:  [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUBLAS failure 3: CUBLAS_STATUS_ALLOC_FAILED ; GPU=0 ; hostname=DESKTOP-J2QDS4A ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_execution_provider.cc ; line=168 ; expr=cublasCreate(&cublas_handle_);

### ISSUE THREAD

**Issue by Aruen24** [ZHO-ZHO-ZHO/ComfyUI-InstantID#54]

**Comment by zhoobin021** [comment]
I have the same error, have you found a solution?

**Comment by BrandWai** [comment]
same problem, cant find solution.

**Comment by zhoobin021** [comment]
> same problem, cant find solution.

download CUDA 11.8 toolkit
and cudnn for that version. this solved my problem.
